package ng.monitoring;

import org.simplejavamail.email.Email;
import org.simplejavamail.mailer.Mailer;
import org.simplejavamail.mailer.config.ServerConfig;
import org.simplejavamail.mailer.config.TransportStrategy;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;


/**
 * Created by adam on 8/30/2017.
 */
public class EmailUtils
{
    private static final Logger logger = LoggerFactory.getLogger(EmailUtils.class);

    public static void sendStatsEmail(String aStatsSummary)
    {
        String sServerRunDateTime = DateUtils.getCurrentDateTime();
        String sServerRunDate     = DateUtils.getCurrentDate();
        String sProgramMainClass  = ProgramUtils.getMainClassName();
        String sProgramCWD        = ProgramUtils.getCurrentWorkingDirectory();
        String sServerHostname    = ProgramUtils.getHostname();

        String sSubject = String.format(
            "%s:  Weekly Stats as of %s", sProgramMainClass, sServerRunDate
        );


        String sEmailBody = String.format(
                "W E E K L Y       S T A T I S T I C S       R E P O R T\n\n\n" +
                "%s\n\n\n" +
                "--------------------------------------------------\n" +
                "This email was generated by the following program:\n" +
                "  Program Name:     %s\n" +
                "  Program CWD:      %s\n" +
                "  Server Run Time:  %s\n" +
                "  Server Hostname:  %s\n", aStatsSummary, sProgramMainClass, sProgramCWD, sServerRunDateTime, sServerHostname);

        Email email = new Email();

        email.addNamedToRecipients("Recipient's name", "recipient@yahoo.com");
//        email.addNamedToRecipients("C. Cane", "candycane@candyshop.org");
//        email.addNamedCcRecipients("C. Bo", "chocobo@candyshop.org");
//        email.addRecipients("Tasting Group", Message.RecipientType.BCC, "taster1@cgroup.org;taster2@cgroup.org;tester <taster3@cgroup.org>");
//        email.addBccRecipients("Mr Sweetnose <snose@candyshop.org>");

        email.setFromAddress("no-reply", "no-reply@bogus.com");
        email.setReplyToAddress("no-reply", "no-reply@bogus.com");
        email.setSubject(sSubject);
//        email.setText(sEmailBody);



        // To maintain spacing, we use an old-style <pre>...</pre> tag
        // If the email is displayed as HTML, then it appears as courier
        email.setTextHTML("<pre>" + sEmailBody + "</pre>");

        email.addHeader("X-Priority", 5);
        email.setUseReturnReceiptTo(false);

//        email.signWithDomainKey(privateKeyData, "somemail.com", "selector");

        // NOTE:  To use smtp.gmail.com, we must configure the myname@gmail.com account to allow less secure apps
        //        See https://myaccount.google.com/lesssecureapps
        Mailer mailer = new Mailer(
                new ServerConfig("smtp.gmail.com", 465, "myname@gmail.com", "my password here"), TransportStrategy.SMTP_SSL

        );

        mailer.setDebug(true);
        mailer.sendMail(email);
    }
}
